server {
    listen 80;

    location = / {
        return 301 /women_wellness_selfcare/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /women_wellness_selfcare/index.html;
    }

    error_page 404 /women_wellness_selfcare/index.html;
}
